// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Gist struct {
	ID        string
	Hash      string
	Result    string
	Language  string
	CreatedAt pgtype.Timestamptz
}
